# Question 1

In [1]:
import numpy as np

np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Question 2

In [13]:
import numpy as np


lst = [] 
n = int(input("Enter number of elements : ")) 
for i in range(0, n): 
    ele = int(input())  
    lst.append(ele) # adding the element      
print(lst) 

lst2 = [] 
m = int(input("Enter number of elements : ")) 
for x in range(0, m): 
    elem = int(input())  
    lst2.append(elem) # adding the element      
print(lst2) 

# converting list to array
arr = np.array(lst)
arr2 = np.array(lst2)


arr3=np.concatenate((arr, arr2), axis=0)
print("Concatenated array:", arr3)

print("Sorted array:", np.sort(arr3))

Enter number of elements : 5
8
5
6
9
10
[8, 5, 6, 9, 10]
Enter number of elements : 5
1
2
3
4
5
[1, 2, 3, 4, 5]
Concatenated array: [ 8  5  6  9 10  1  2  3  4  5]
Sorted array: [ 1  2  3  4  5  5  6  8  9 10]


# Question 3

In [14]:
import numpy as np
 

arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
print("Array is of type: ", type(arr)) 
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Size of array:  6


# Question 4

In [30]:
import numpy as np
a = np.arange(10)
print(a)
print(a.shape)

print(a[:, np.newaxis])
print(a[:, np.newaxis].shape)

print(np.expand_dims(a, 1))
print(np.expand_dims(a, 0))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1 2 3 4 5 6 7 8 9]]


# Question 5

In [32]:
import numpy as np 

a = np.array([[1, 2], [3, 4]]) 
b = np.array([[5, 6], [7, 8]]) 
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b))) 

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


# Question 6

In [45]:
a_list = [1, 1, 2, 2, 3]
a_set = set(a_list)
print(a_set)
number_of_unique_values = len(a_set)
print(number_of_unique_values)

{1, 2, 3}
3
